services:
  simplegallery:
    build: '.'
    restart: "unless-stopped"
    image: "samburney/simplegallery:latest"
    depends_on:
      - db
    environment:
      PHP_UPLOAD_MAX_FILESIZE: "2048M"
      PHP_POST_MAX_SIZE: "2048M"
      PHP_MEMORY_LIMIT: "1024M"
      DB_DRIVER: "mysql"
      DB_HOST: "db"
      DB_DATABASE: "${DB_NAME}"
      DB_USERNAME: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./data/files/:/var/www/simplegallery/public/files"
    ports:
      - ${SIMPLEGALLERY_HOST_PORT:-8081}:80

  db:
    image: mariadb:11.8-noble
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-hlocalhost", "-u${DB_USER}", "-p${DB_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 20

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "${ADMINER_HOST_PORT:-8080}:8080"
    depends_on:
      - db

volumes:
  db_data:
