#!/usr/bin/with-contenv bash

# Generate app key
cd /var/www/simplegallery

php artisan key:generate

# Sleep for a bit to allow MySQL DB to start...
sleep 10

# Check that database doesn't already exist
mysqlshow -h$DB_HOST -u$DB_USERNAME -p$DB_PASSWORD $DB_DATABASE > /dev/null 2>&1
DB_NOT_EXISTS=$?

if [ $DB_NOT_EXISTS != 0 ] ; then
	echo "DB $DB_DATABASE not found, creating and populating..."

	mysqladmin -h$DB_HOST -u$DB_USERNAME -p$DB_PASSWORD create $DB_DATABASE
	php artisan migrate --force
fi
